# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies, including dev dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Install ts-node globally
RUN npm install -g tsx

# Expose the port your app runs on
EXPOSE 3000

# Use Nodemon with ts-node to watch for file changes and restart on updates
CMD ["npx", "nodemon", "--watch", ".", "--exec", "tsx", "src/app.ts"]
